name: panda-api
# x-env-file: &env_file
#   - .env.example

services:
  mysql:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
    networks:
      - panda-api-network
    # env_file: *env_file
  consul:
    image: hashicorp/consul:1.22
    container_name: consul-server
    command: consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - panda-api-network
    # env_file: *env_file
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qwer1234
    # env_file: *env_file
    
networks:
  panda-api-network:
    driver: bridge
